// Import Firebase using browser-ready CDN links (ES Modules)
import { initializeApp } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js";
import { getFirestore, collection, addDoc, deleteDoc, doc, onSnapshot } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js";

// Connected directly to your 'student-management-syste-27b4d' Firebase project
const firebaseConfig = {
  apiKey: "AIzaSyCu9OZHB-fUwqKaVWkIGUYOg7wY83jte9Y",
  authDomain: "student-management-syste-27b4d.firebaseapp.com",
  projectId: "student-management-syste-27b4d",
  storageBucket: "student-management-syste-27b4d.firebasestorage.app",
  messagingSenderId: "780857535653",
  appId: "1:780857535653:web:37eca357dab470262e714c",
  measurementId: "G-LNT761R8GW"
};

// Initialize Firebase & Firestore database connections
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
const studentsCollection = collection(db, "students");

document.addEventListener('DOMContentLoaded', () => {
    // 1. Manage Simulated Login Form Routes
    const loginForm = document.getElementById('loginForm');
    if (loginForm) {
        loginForm.addEventListener('submit', (e) => {
            e.preventDefault();
            const email = document.getElementById('email').value;
            const password = document.getElementById('password').value;
            if (email && password) {
                // Routes cleanly to your dashboard file layout
                window.location.href = 'dashboard.html';
            }
        });
    }

    // 2. Real-time Database Sync for Enrolled Students Table Directory
    const studentTableBody = document.getElementById('studentTableBody');
    const studentForm = document.getElementById('studentForm');

    if (studentTableBody) {
        // Automatically syncs the UI whenever changes happen in your Firebase Firestore cloud database
        onSnapshot(studentsCollection, (snapshot) => {
            studentTableBody.innerHTML = '';
            snapshot.forEach((documentSnapshot) => {
                const student = documentSnapshot.data();
                const docId = documentSnapshot.id; // Unique document ID generated by Firebase
                
                const row = document.createElement('tr');
                row.innerHTML = `
                    <td><strong>${student.id || ''}</strong></td>
                    <td>${student.name || ''}</td>
                    <td>${student.course || ''}</td>
                    <td>${student.email || ''}</td>
                    <td>
                        <button class="btn btn-danger delete-btn" data-id="${docId}">
                            <i class="fa-regular fa-trash-can"></i> Delete
                        </button>
                    </td>
                `;
                studentTableBody.appendChild(row);
            });

            // Handle dynamic real-time student document deletions from Cloud Firestore
            document.querySelectorAll('.delete-btn').forEach(btn => {
                btn.addEventListener('click', async (e) => {
                    const targetDocId = e.target.closest('.delete-btn').dataset.id;
                    try {
                        await deleteDoc(doc(db, "students", targetDocId));
                    } catch (error) {
                        console.error("Error deleting from cloud database: ", error);
                    }
                });
            });
        });
    }

    // 3. Register and Send New Student Profile directly to Firebase Collection
    if (studentForm) {
        studentForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            
            const studentData = {
                id: document.getElementById('stuId').value,
                name: document.getElementById('stuName').value,
                course: document.getElementById('stuCourse').value,
                email: document.getElementById('stuEmail').value,
                timestamp: new Date()
            };

            try {
                // Firebase creates the collection automatically upon saving your first profile document record
                await addDoc(studentsCollection, studentData);
                studentForm.reset();
            } catch (error) {
                console.error("Error writing data profile to database collection: ", error);
            }
        });
    }

    // Sidebar Sign-Out UI router button link navigation
    const logoutBtn = document.getElementById('logoutBtn');
    if (logoutBtn) {
        logoutBtn.addEventListener('click', (e) => {
            e.preventDefault();
            window.location.href = 'login.html';
        });
    }
});
